### ISSUE TITLE
Formatting is not proper on iPhone XS models

### ISSUE THREAD

**Issue by akshaynexus** [PIVX-Project/PIVX-iOS#10]
As per code,the padding and formatting for the iphone x only applies to iphone x ,however oon iphonexs ui looks out of place,simple solution is to check if its a x,xs or xmax then to apply is iphonex bool to formatting.

**Comment by Fuzzbawls** [comment]
please provide some screenshots

**Comment by Fuzzbawls** [comment]
nevermind...see #12
