### ISSUE TITLE
I am facing two issues - ExternalBuildToolExecution - CompileSwift failed 

### ISSUE THREAD

**Issue by osamainam777** [PIVX-Project/PIVX-iOS#23]
After downloading, cleaning, reinstall pods and updating pods. Im still facing with these issue for the project. It seems like some files are missing in the project. 
Can you help me?

- fatal: not a git repository (or any of the parent directories): .git

Command ExternalBuildToolExecution failed with a nonzero exit code
<img width="739" alt="Screenshot 2019-08-09 at 12 22 54 PM" src="https://user-images.githubusercontent.com/17943494/62761590-74493800-baa0-11e9-94fb-5f65c2a6cd88.png">

- Command CompileSwift failed with a nonzero exit code

**Comment by akshaynexus** [comment]
Clone the repo with git clone instead of downloading via the download as zip option

**Comment by Fuzzbawls** [comment]
closing, no further response
