### ISSUE TITLE
Mobile wallet non working

### ISSUE THREAD

**Issue by Pisti777** [PIVX-Project/PIVX-iOS#34]
the mobile wallet is not available and the computer cannot be downloaded to the software you will unlock these wallets because nothing is going on. pious behavior of members of the pvix coin support team full ignorance.

**Comment by Pisti777** [comment]
okropne zachowanie zespołu wsparcia monet pvix pełna ignorancja

**Comment by Fuzzbawls** [comment]
the wallet works, you were instructed in multiple recovery methods via discord but refused to follow any one of them. closing this.
